version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "mailup-integration"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-muhifkyo4xry"
s3_prefix = "mailup-integration"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Timeout=\"40\" MemorySize=\"128\" Entrypoint=\"cmcc.mailup.core\""
image_repositories = []
